# Generated by Django 5.0 on 2023-12-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_repuesto_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Repuesto',
        ),
    ]
