# Generated by Django 5.0 on 2023-12-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_ventiladores_task_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventiladores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='ventiladores/')),
            ],
        ),
    ]
