# Generated by Django 5.0 on 2023-12-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_task_category_remove_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='search_field',
        ),
    ]
