# Generated by Django 5.0 on 2023-12-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_project_description_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imagenes',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='imagenes_task',
            field=models.ImageField(default='', upload_to='task_imagenes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Descripción predeterminada'),
        ),
    ]
