# Generated by Django 5.0 on 2023-12-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_project_imagenes_task_imagenes_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modelo_vt',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
